<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFao6ue1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFao6ue1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFao6ue1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFao6ue1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFao6ue1\App_KernelDevDebugContainer([
    'container.build_hash' => 'Fao6ue1',
    'container.build_id' => '0ca1c1df',
    'container.build_time' => 1732180542,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFao6ue1');
